package euler

//Fibonacci sequence is generated by adding the previous two terms
func Fibonacci(index int) int {

	if index == 1 || index == 0{
		return 1
	}

	var a , b, result int = 0, 1, 0
	for i:= 2; i <= index; i++ {
		a, b = b, a + b
		result = b
	}
	return result
}

//It calculates even Fibonacci term whose value not exceed a given number, here is limit
func EvenTermFibonnaci(limit int) int{

	var total, i int
	for Fibonacci(i) < limit {
		if Fibonacci(i) % 2 == 0 {
			total += Fibonacci(i)
		} 
		i++
	}
	return total
}
